name: PlatformDirs CI

on:
  push:
  pull_request:

jobs:
  build-test:
    name: Test on Ubuntu, macOS, Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure & Build
      run: |
        cmake -B build
        cmake --build build

    - name: Run Test
      run: ./build/test_platform_dirs
      shell: bash
