name: Windows CI

on:
  push:
  pull_request:

jobs:
  build-test:
    name: Test on Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure & Build
      run: |
        cmake -B build
        cmake --build build

    - name: Run Test
      run: cmd.exe /c build\\test_platform_dirs.exe
      shell: bash
